<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { useToast } from "primevue/usetoast";
import TeacherLayout from "@/layouts/TeacherLayout.vue";
import Skeleton from "@/components/ui/Skeleton.vue";
import { practiqApi } from "@/api/request/server";

const toast = useToast(); const loading = ref(true); const saving = ref(false);
const form = reactive({ email: "", phone: "", whatsapp: "" });
async function load(){ try { const { data } = await practiqApi.get("/site-contact"); Object.assign(form, data.data); } catch { toast.add({severity:"error",summary:"Error",detail:"No se pudo cargar contacto",life:3000}); } finally { loading.value=false; } }
async function save(){ if(saving.value)return; saving.value=true; try { await practiqApi.put("/site-contact",form); toast.add({severity:"success",summary:"Contacto guardado",life:2500}); } catch { toast.add({severity:"error",summary:"Error",detail:"No se pudo guardar",life:3000}); } finally { saving.value=false; } }
onMounted(load);
</script>
<template><TeacherLayout><main class="page"><header class="page-header"><div><p class="eyebrow">Landing pública</p><h1>Contacto institucional</h1><p>Estos datos aparecen en el plan para escuelas e institutos.</p></div></header><Skeleton v-if="loading" height="300px" /><form v-else class="settings-card" @submit.prevent="save"><label>Email<input v-model.trim="form.email" type="email" required /></label><label>Teléfono<input v-model.trim="form.phone" type="tel" required /></label><label>WhatsApp URL<input v-model.trim="form.whatsapp" type="url" required placeholder="https://wa.me/549..." /></label><button :disabled="saving">{{ saving ? "Guardando…" : "Guardar contacto" }}</button></form></main></TeacherLayout></template>
<style scoped>.page{max-width:1180px;margin:0;padding:24px 28px 40px}.eyebrow{font-size:var(--font-kicker);font-weight:800;letter-spacing:.09em;color:var(--practiq-violet);text-transform:uppercase}h1{margin:3px 0 0;color:var(--text-heading);font-size:clamp(1.55rem,2.5vw,2rem)}header p:last-child{max-width:660px;margin:7px 0 0;color:var(--text-secondary);line-height:1.55}.settings-card{display:grid;max-width:760px;gap:18px;margin-top:16px;padding:24px;border:1px solid var(--surface-border);border-radius:var(--radius-xl);background:var(--surface-card);box-shadow:var(--shadow-card)}label{display:grid;gap:8px;color:var(--text-heading);font-size:var(--text-sm);font-weight:800}input{min-height:48px;padding:11px 13px;border:1px solid var(--surface-border);border-radius:var(--radius-md);background:var(--surface-ground);color:var(--text-primary);font:inherit}input:focus{outline:none;border-color:var(--practiq-violet);box-shadow:0 0 0 3px rgba(var(--practiq-violet-rgb),.12)}button{min-height:46px;justify-self:start;padding:10px 20px;border:0;border-radius:var(--radius-md);background:var(--practiq-violet);box-shadow:var(--shadow-violet);color:#fff;font-weight:800;cursor:pointer}button:disabled{opacity:.6}@media(max-width:600px){.page{padding:20px 16px 36px}h1{font-size:24px;line-height:1.18}header p:last-child{font-size:14px}.settings-card{gap:16px;margin-top:22px;padding:18px 16px}input{min-height:48px;font-size:16px}button{width:100%;min-height:48px;justify-self:stretch}}</style>
